# Generated by Django 3.0.2 on 2020-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_auto_20200112_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventype',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Birthday party', 'Birthday party'), ('Lecture', 'Lecture'), ('Shopping time', 'Shopping time'), ('Netflix alert', 'Netflix alert'), ('Other', 'Other')], default='O', max_length=20),
        ),
    ]
