# Generated by Django 3.0 on 2020-01-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('commentschema_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QuestionSite.CommentSchema')),
            ],
            bases=('QuestionSite.commentschema',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=' ', max_length=100)),
                ('description', models.TextField(default=' ', max_length=255)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(default='', max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('related_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSite.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('commentschema_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='QuestionSite.CommentSchema')),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSite.MainComment')),
            ],
            bases=('QuestionSite.commentschema',),
        ),
        migrations.AddField(
            model_name='maincomment',
            name='related_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionSite.Question'),
        ),
    ]
