# Generated by Django 3.0.2 on 2020-01-19 22:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestionSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 23, 47, 38, 214122)),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
