# Generated by Django 3.0.2 on 2020-01-19 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionSite', '0002_auto_20200119_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 23, 53, 11, 178634)),
        ),
    ]
